### ISSUE TITLE
Doesn't work across three different browsers

### ISSUE THREAD

**Issue by enlguy** [BuilderIO/figma-html#105]
Any time I "Generate Code," it crashes the browser.  Have tried many times.  Says "out of memory."  I have 12GB RAM and nothing else running.... 
Browser is Comodo IceDragon.  I've tried in Edge, and plugin menu doesn't even show up there.  Crashes Chrome as well.  Got it to work ONCE in Chrome, but said if I'm not using autolayout (what's the point of the tool, if I can't export code from a design file drawn the way it should be?), it won't do anything.

**Comment by samijaber** [comment]
> but said if I'm not using autolayout, it won't do anything

Yes, as explained in our documentation, using autolayout is a constraint to be able to generate code using the plugin. See https://www.builder.io/c/docs/import-from-figma for more information
