### ISSUE TITLE
TypeError - on site import 

### ISSUE THREAD

**Issue by imperatorm** [BuilderIO/figma-html#110]
First off amazing work on this. 
![image](https://user-images.githubusercontent.com/32312789/177772592-ae330659-1d5b-497b-88cb-2f686ccff5b2.png)
It seems on quite a few sites the same error message pops up. Sometimes on pretty basic pages 

`TypeError: Cannot read properties of undefined (reading "map")`

Does anyone know what this is about?

**Comment by Leandro4maker** [comment]
Também estou tendo esse problema, desde ontem (07/06/2022).
<img width="293" alt="Captura de Tela 2022-07-07 às 09 51 50" src="https://user-images.githubusercontent.com/86621594/177778125-2195c410-224f-4bae-a191-3542e3805c45.png">

**Comment by MikeGel** [comment]
<img width="1673" alt="Снимок экрана 2022-07-07 в 21 22 52" src="https://user-images.githubusercontent.com/108891619/177842865-9e507e62-130c-4d5b-bb6e-8a91049ea82c.png">
https://www.loxone.com/ 
Это абсолютно с любым сайтом, не только с этим.

**Comment by Leandro4maker** [comment]
> Please provide the sites this is happening on, or else we cannot help in any way.


As far as I've tested, it doesn't have a specific site. Since yesterday, any link I put gives this message.

**Comment by Leandro4maker** [comment]
> Please provide the sites this is happening on, or else we cannot help in any way.

I tested with:

https://www.royalz.com.br
http://ww.4maker.digital
http://www.lego.com.br
http://www.spicy.com.br
http://www.amesofa.com.br
http://www.puramagia.com.br

**Comment by MikeGel** [comment]
> > Пожалуйста, укажите сайты, на которых это происходит, иначе мы ничем не сможем помочь.
> 
> Насколько я проверял, у него нет конкретного сайта. Со вчерашнего дня любая ссылка, которую я помещаю, дает это сообщение.

У МЕНЯ ТОТ ЖЕ РЕЗУЛЬТАТ

**Comment by samijaber** [comment]
We just deployed a fix to our API endpoint. We believe it should fix these issues with everybody. Let me know if you are still seeing any problems!

**Comment by MikeGel** [comment]
> Мы только что развернули исправление для нашей конечной точки API. Мы считаем, что это должно решить эти проблемы со всеми. Дайте мне знать, если вы все еще видите какие-либо проблемы!

Все супер! Работает! Спасибо!
