### ISSUE TITLE
Launched locally and it does not generate code or json

### ISSUE THREAD

**Issue by Galvotas** [BuilderIO/figma-html#111]
**Describe the bug**
Error when trying to either generate or download code via tool. I also got error when adding plugin according to readme file.

**To Reproduce**
1. Follow Readme file 
2. Running project with npm run dev(useDev is set to true)
3. Opening figma app and selecting some item, set it to auto layout. Then clicking right and Plugins > Development > HTML <> FIGMA
4. Clicking download json or generate code and always receive the same error

**Expected behavior**
Expected to test the tool and try downloading or generating the code.

**Screenshots**
<img width="1728" alt="Screenshot 2022-07-14 at 21 36 06" src="https://user-images.githubusercontent.com/60818031/179059359-946aa230-4de2-45e4-9310-c147806d645f.png">

<img width="650" alt="Screenshot 2022-07-14 at 21 48 15" src="https://user-images.githubusercontent.com/60818031/179060056-50e52807-d511-4941-b9ea-4f725c903c80.png">

**Comment by samijaber** [comment]
`useDev` should not be set to `true` for outside folks. It is only set to `true` by internal Builder employees and will break your local env if you do so, so you'll want to keep it `false`
