### ISSUE TITLE
Unable to Upload JSON in Figma Desktop app for mac

### ISSUE THREAD

**Issue by sudharsan1994** [BuilderIO/figma-html#112]
**Describe the bug**
Upload here button didnt work; unable to upload the doc to Figma
**To Reproduce**
1. Downloaded a JSON from Chrome plugin
2. Opened Figma
3. Ran plugin
4. Clicked "Upload here" but there was no dialog box

**Expected behavior**
A Dialog box to choose file should open
**Screenshots**

**Additional context**

**Comment by samijaber** [comment]
What machine, OS, etc. are you using? I just tested this and it works fine:

https://www.loom.com/share/58a14b404b83439690a40b9af6b1c14d

**Comment by betssofie** [comment]
Faced the same problem. Problem disappeared after upgrading Figma to the latest version.

**Comment by sudharsan1994** [comment]
Its working fine post Figma update

thank you
