### ISSUE TITLE
does not importing any images

### ISSUE THREAD

**Issue by MiaCCA** [BuilderIO/figma-html#123]
**Describe the bug**
I download .json file from Chrome extension. But when I imported it to Figma all the images on the web page is displayed as a grey box. 

**Screenshots**
<img width="392" alt="Screen Shot 2022-08-03 at 12 29 57 AM" src="https://user-images.githubusercontent.com/62979631/182550258-32a1f850-2844-4727-9b6e-acc882ff1800.png">

**Comment by steve8708** [comment]
Thanks for reporting @MiaCCA, we're on it!

**Comment by samijaber** [comment]
This should now be fixed @MiaCCA! We tested and images are back
