### ISSUE TITLE
JSON not generated from Google Chrome Extension

### ISSUE THREAD

**Issue by angyb** [BuilderIO/figma-html#128]
HTML to Figma extension installed in Google Chrome (latest version) on MacOS 12.5.1 (latest version) is not generating a JSON file when CAPTURE PAGE button is clicked (and it acts like it is working and the Done! page appears).

I've tried this on 2 different Macs and am experiencing the problem on both. I successfully used this extension previously on one of these computers, but it's not working now. I've tried it on several different types of pages on the Internet (not local files).

Am I the only one experiencing this? Is there a setting in Chrome that I can change or something else I can try?

**Comment by benbenazzi** [comment]
having similar issue. Thanks for your help!

**Comment by steve8708** [comment]
ah! thanks so much for reporting, just submitted a new version to the chrome app store with the fix, should go live probably in the next day or so
