### ISSUE TITLE
Exceeded Current Qouta

### ISSUE THREAD

**Issue by VickRoopram** [BuilderIO/figma-html#143]
**Describe the bug**
I have never used Builder.io before, I entered my open ai secret key and prompt then clicked generate. It would not generate a prompt. Just gives me a error that I have exceeded my quota. I can use open ai, chat gpt all fine, this is the only security key I have ever made so I do not understand... Do I need to pay for this plugin just to try it out?

**To Reproduce**
1.Entered Prompt
2.Entered site I want it to base style from
3.Entered SK from open ai
4.clicked generate

**Expected behavior**
Generate some sort of page in Figma based on my prompts 

**Screenshots**
![Screenshot 2023-04-18 143941](https://user-images.githubusercontent.com/66904370/232780077-3a8a72af-3814-4ff6-8f6b-1b6344daa4e2.png)

**Additional context**

**Comment by samijaber** [comment]
Yes, you need to pay OpenAI. ChatGPT is free but using the OpenAI API through secret keys isn't. Check https://platform.openai.com/account/usage and make sure you have credits in your account
