### ISSUE TITLE
Browser extensions generate incorrect file format

### ISSUE THREAD

**Issue by TimotiusAnrez** [BuilderIO/figma-html#152]
**Describe the bug**
Browser extensions generate Adobe After Effect JSON file instead of .h2d file format. 

**To Reproduce**
1. Install HTML to Figma browser extensions on chromium base browser
2. Start the browser extensions
3. Use capture page feature
4. Adobe After Effect JSON file is downloaded instead of .h2d file format

**Expected behavior**
Base on the documentation, the extensions supposed to generate .h2d file format automatically

**Screenshots**
Got this:
![image](https://github.com/BuilderIO/figma-html/assets/71978054/b7e07767-b6b5-40e1-aba1-2dcb56886d62)
Instead of this:
![image](https://github.com/BuilderIO/figma-html/assets/71978054/5637c96a-65b0-403e-8fbc-645d390735c8)

**Additional context**
Haven't tried in other chromium base browser, currently this bug happened in opera web browser. Due there is no option to upload other kind of file format other than .h2d file format, the plugin cannot be used for capturing private page since the browser plugin not generating file format that can be used for figma plugin.

**Comment by steve8708** [comment]
I think you have the wrong repo - `html.to.design` is not this project, we generate `.json` files not `.h2d` files. From what I can tell, html.to.design copied our work here, but their work is closed source and paid, as opposed to contributing their improvements back

**Comment by wanghaisheng** [comment]
@steve8708  is this repo no long maintained?
