### ISSUE TITLE
NO RESULTS FOUND....when searched "html to figma"

### ISSUE THREAD

**Issue by SubrataJZ** [BuilderIO/figma-html#44]
**NO RESULTS FOUND** When search for "html to figma" in the search box of figma.
![image](https://user-images.githubusercontent.com/20490476/93446979-197f3400-f88f-11ea-8332-fff3ab1ae67d.png)

What can i do to fix it ?

**Comment by steve8708** [comment]
hey @SubrataJZ - you sure you have the plugin installed? the menu is not something we have control over - if the plugin is installed then figma will have it in the menu, and if not theres not a ton we can do

if you definitely have it installed but it won't show in the menu, perhaps contact figma support?

**Comment by rodrigoslino** [comment]
![image](https://user-images.githubusercontent.com/24231369/95469687-4f777b80-0956-11eb-8452-bd30c07e4ea9.png)

Go to this link below and install:
https://www.figma.com/community/search?model_type=public_plugins&q=html%20to%20figma
