### ISSUE TITLE
Seems that plugin doesn't work

### ISSUE THREAD

**Issue by soulwasted** [BuilderIO/figma-html#54]
Hi,

looks like that plugin in Figma is not working anymore.
Can somebody have a look on this pls?

Thanks!

pepę

**Comment by soulwasted** [comment]
Seems it works again! :D

**Comment by steve8708** [comment]
Thanks for reporting @soulwasted - I think we may have a sporadic issue. I'm pushing what I believe is the fix now, but so I can test around, can you share with me the URL you used that didn't work for a period before? I can see if I can reproduce any longer with the latest fix
