### ISSUE TITLE
Deleted Figma design

### ISSUE THREAD

**Issue by deirdrerohr** [BuilderIO/figma-html#59]
https://www.figma.com/file/zi94yBRIXN1t9UIlxDfAbd/Untitled

There were 3 days worth of designs on this page.  I uploaded the plugin and now they are gone.  The background for the whole project is still there but everything else is gone.

**Comment by steve8708** [comment]
Hey @deirdrerohr - we've never seen such an issue created by our plugin, but regardless have you tried using Figma' history feature to go back in history? https://help.figma.com/hc/en-us/articles/360038006754-View-a-file-s-version-history

**Comment by deirdrerohr** [comment]
I just found it in the history feature!  Thanks for the tip.  All backed up now.  I did have a problem installing the plugin.  It took a few attempts and then the file was gone.  Maybe it was on Figma's side?
