### ISSUE TITLE
"HTML -> Figma" readme no longer compatiable with Figma UI

### ISSUE THREAD

**Issue by PMLP-novo** [BuilderIO/figma-html#71]
Figma's desktop app (at least for Windows) is no longer compatiable with the current Figma's UI and as beginner in Figma it is unclear how you import a json document. I think it is what is trying to be communicated in https://github.com/BuilderIO/figma-html/issues/68

Current UI:
![image](https://user-images.githubusercontent.com/54025656/125929549-2a371e45-582b-4ec0-8ef7-fc516cf9aba2.png)

And when searching for html there are no place to import the json file: 
![image](https://user-images.githubusercontent.com/54025656/125929621-90c78875-f406-4178-9c6c-25328b3d28e7.png)

So at the current moment following the documentation it is not posible to import the HTML into Figma

**Comment by PMLP-novo** [comment]
Sorry I was an idiot I did not install the plugin for figma as well. For a complete noob like me it could be nice if the documentation mentioned that you need both the Figma plugin and the Chrome plugin

**Comment by steve8708** [comment]
no worries, will close this out :D
