### ISSUE TITLE
Does not import images or svg's anymore

### ISSUE THREAD

**Issue by cZeaushe** [BuilderIO/figma-html#73]
With the Chrome extension and the plugin for Figma it does not import any images or svg's of the page anymore. 

The imported designs look very broken.

Happens on windows and mac.

Example:
![example](https://user-images.githubusercontent.com/69605808/128947513-f577e83a-297b-4038-b9b8-090dbc2999c9.jpg)

**Comment by steve8708** [comment]
Thanks for reporting @cZeaushe ! We have found the issue and are hoping to resolve today. Will report back

**Comment by steve8708** [comment]
Ok! Should be fixed now, thank you all for your patience and let us know if you run into any future issues 🙏
